import type { Carrier, CountryCode, ParcelPreset } from './types'

export const IN_TO_CM = 2.54
export const DESI_VOLUME_DIVISOR = 3000
export const DEFAULT_EXCHANGE_RATE = 7.25
export const FX_REFRESH_INTERVAL_MS = 30 * 60 * 1000

export const COUNTRY_NAMES: Record<string, string> = {
  US: 'United States',
  AU: 'Australia',
  CA: 'Canada',
  MX: 'Mexico',
}

export const PRESETS: ParcelPreset[] = [
  { id: 'envelope', labelKey: 'preset_envelope', l: 30, w: 22, h: 3, weight: 0.15 },
  { id: 'small', labelKey: 'preset_small', l: 20, w: 15, h: 10, weight: 0.3 },
  { id: 'medium', labelKey: 'preset_medium', l: 30, w: 20, h: 15, weight: 0.8 },
  { id: 'large', labelKey: 'preset_large', l: 40, w: 30, h: 20, weight: 2.0 },
  { id: 'shoe', labelKey: 'preset_shoe', l: 35, w: 22, h: 14, weight: 1.2 },
  { id: 'custom', labelKey: 'preset_custom', l: null, w: null, h: null, weight: null },
]

function nowISO(): string {
  return new Date().toISOString()
}

export const DEFAULT_CARRIERS: Record<string, Carrier> = {
  liumai: {
    id: 'liumai',
    name: 'LIUMAI Express Supply Chain',
    effectiveDate: '2026-01-31',
    rating: 0,
    notes: '',
    isActive: true,
    createdAt: nowISO(),
    updatedAt: nowISO(),
    services: [
      {
        id: 'liumai_priority_l01',
        name: 'Express Priority L01',
        code: '20093',
        country: 'CA' as CountryCode,
        deliveryDays: { min: 6, max: 9 },
        type: 'Express',
        isActive: true,
        volumetricDivisor: 8000,
        maxWeight: 30,
        maxDimensions: { l: 55, w: 40, h: 35 },
        maxVolume: 0.056,
        oversizeSurcharge: 120,
        maxCompensation: { beforeTracking: 400, afterTracking: 400 },
        rates: [
          { minWeight: 0, maxWeight: 0.2, minCharge: 0.05, ratePerKg: 122, handlingFee: 30 },
          { minWeight: 0.2, maxWeight: 0.3, ratePerKg: 122, handlingFee: 32 },
          { minWeight: 0.3, maxWeight: 0.45, ratePerKg: 122, handlingFee: 35 },
          { minWeight: 0.45, maxWeight: 0.7, ratePerKg: 112, handlingFee: 48 },
          { minWeight: 0.7, maxWeight: 2, ratePerKg: 112, handlingFee: 48 },
          { minWeight: 2, maxWeight: 30, ratePerKg: 112, handlingFee: 48 },
        ],
      },
      {
        id: 'liumai_standard_l01',
        name: 'Express Standard L01',
        code: '20090',
        country: 'CA' as CountryCode,
        deliveryDays: { min: 8, max: 15 },
        type: 'Economy',
        isActive: true,
        volumetricDivisor: 8000,
        maxWeight: 10,
        maxDimensions: { l: 55, w: 40, h: 35 },
        maxVolume: 0.056,
        oversizeSurcharge: 120,
        maxCompensation: { beforeTracking: 300, afterTracking: 300 },
        rates: [
          { minWeight: 0, maxWeight: 0.1, minCharge: 0.05, ratePerKg: 116, handlingFee: 24 },
          { minWeight: 0.1, maxWeight: 0.2, ratePerKg: 116, handlingFee: 20 },
          { minWeight: 0.2, maxWeight: 0.45, ratePerKg: 116, handlingFee: 18 },
          { minWeight: 0.45, maxWeight: 0.7, ratePerKg: 116, handlingFee: 18 },
          { minWeight: 0.7, maxWeight: 2, ratePerKg: 116, handlingFee: 12 },
          { minWeight: 2, maxWeight: 10, ratePerKg: 116, handlingFee: 12 },
        ],
      },
      {
        id: 'liumai_standard',
        name: 'Express Standard',
        code: '3781',
        country: 'CA' as CountryCode,
        deliveryDays: { min: 8, max: 15 },
        type: 'Economy',
        isActive: true,
        volumetricDivisor: 8000,
        maxWeight: 10,
        maxDimensions: { l: 55, w: 40, h: 35 },
        maxVolume: 0.056,
        oversizeSurcharge: 120,
        maxCompensation: { beforeTracking: 150, afterTracking: 150 },
        rates: [
          { minWeight: 0, maxWeight: 0.1, minCharge: 0.05, ratePerKg: 119, handlingFee: 24 },
          { minWeight: 0.1, maxWeight: 0.2, ratePerKg: 119, handlingFee: 20 },
          { minWeight: 0.2, maxWeight: 0.45, ratePerKg: 119, handlingFee: 18 },
          { minWeight: 0.45, maxWeight: 0.7, ratePerKg: 119, handlingFee: 18 },
          { minWeight: 0.7, maxWeight: 2, ratePerKg: 119, handlingFee: 12 },
          { minWeight: 2, maxWeight: 10, ratePerKg: 119, handlingFee: 12 },
        ],
      },
    ],
  },
  js_express: {
    id: 'js_express',
    name: 'JS Express',
    effectiveDate: '2026-03-12',
    rating: 0,
    notes: '',
    isActive: true,
    createdAt: nowISO(),
    updatedAt: nowISO(),
    services: [
      {
        id: 'js_au_z1_gen', name: 'AU Zone 1 — General Cargo', code: 'CAAU-GEN-Z1',
        country: 'AU' as CountryCode, zone: 'Zone 1', deliveryDays: { min: 8, max: 12 }, type: 'DDP',
        isActive: true, volumetricDivisor: 8000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 33, handlingFee: 20 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 33, handlingFee: 21 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 33, handlingFee: 21 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 33, handlingFee: 22 },
          { minWeight: 2, maxWeight: 5, ratePerKg: 33, handlingFee: 25 },
        ],
      },
      {
        id: 'js_au_z2_gen', name: 'AU Zone 2 — General Cargo', code: 'CAAU-GEN-Z2',
        country: 'AU' as CountryCode, zone: 'Zone 2', deliveryDays: { min: 8, max: 12 }, type: 'DDP',
        isActive: true, volumetricDivisor: 8000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 33, handlingFee: 26 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 33, handlingFee: 26 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 33, handlingFee: 26 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 33, handlingFee: 28 },
          { minWeight: 2, maxWeight: 5, ratePerKg: 33, handlingFee: 38 },
        ],
      },
      {
        id: 'js_au_z3_gen', name: 'AU Zone 3 — General Cargo', code: 'CAAU-GEN-Z3',
        country: 'AU' as CountryCode, zone: 'Zone 3', deliveryDays: { min: 8, max: 12 }, type: 'DDP',
        isActive: true, volumetricDivisor: 8000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 33, handlingFee: 47 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 33, handlingFee: 47 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 33, handlingFee: 66 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 33, handlingFee: 67 },
          { minWeight: 2, maxWeight: 5, ratePerKg: 33, handlingFee: 102.4 },
        ],
      },
      {
        id: 'js_au_z1_dg', name: 'AU Zone 1 — Battery/DG', code: 'CAAU-DG-Z1',
        country: 'AU' as CountryCode, zone: 'Zone 1', deliveryDays: { min: 10, max: 15 }, type: 'DDP-DG',
        isActive: true, volumetricDivisor: 8000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 53, handlingFee: 20 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 53, handlingFee: 21 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 53, handlingFee: 21 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 53, handlingFee: 22 },
          { minWeight: 2, maxWeight: 4, ratePerKg: 53, handlingFee: 25 },
          { minWeight: 4, maxWeight: 5, ratePerKg: 53, handlingFee: 25 },
        ],
      },
      {
        id: 'js_au_z2_dg', name: 'AU Zone 2 — Battery/DG', code: 'CAAU-DG-Z2',
        country: 'AU' as CountryCode, zone: 'Zone 2', deliveryDays: { min: 10, max: 15 }, type: 'DDP-DG',
        isActive: true, volumetricDivisor: 8000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 53, handlingFee: 26 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 53, handlingFee: 26 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 53, handlingFee: 26 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 53, handlingFee: 28 },
          { minWeight: 2, maxWeight: 4, ratePerKg: 53, handlingFee: 38 },
          { minWeight: 4, maxWeight: 5, ratePerKg: 53, handlingFee: 38 },
        ],
      },
      {
        id: 'js_au_z3_dg', name: 'AU Zone 3 — Battery/DG', code: 'CAAU-DG-Z3',
        country: 'AU' as CountryCode, zone: 'Zone 3', deliveryDays: { min: 10, max: 15 }, type: 'DDP-DG',
        isActive: true, volumetricDivisor: 8000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 53, handlingFee: 47 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 53, handlingFee: 47 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 53, handlingFee: 66 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 53, handlingFee: 67 },
          { minWeight: 2, maxWeight: 5, ratePerKg: 53, handlingFee: 102.4 },
        ],
      },
      {
        id: 'js_ca_gen', name: 'Canada — General Cargo', code: 'CAAU-GEN-CA',
        country: 'CA' as CountryCode, deliveryDays: { min: 8, max: 12 }, type: 'DDP',
        isActive: true, volumetricDivisor: 8000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.1, minCharge: 0.05, ratePerKg: 48, handlingFee: 22 },
          { minWeight: 0.1, maxWeight: 0.24, ratePerKg: 48, handlingFee: 22 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 53, handlingFee: 22 },
          { minWeight: 0.5, maxWeight: 1, ratePerKg: 53, handlingFee: 25 },
          { minWeight: 1, maxWeight: 1.5, ratePerKg: 56, handlingFee: 25 },
          { minWeight: 1.5, maxWeight: 5, ratePerKg: 56, handlingFee: 25 },
        ],
      },
      {
        id: 'js_ca_dg', name: 'Canada — Battery/DG', code: 'CAAU-DG-CA',
        country: 'CA' as CountryCode, deliveryDays: { min: 10, max: 15 }, type: 'DDP-DG',
        isActive: true, volumetricDivisor: 8000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.1, minCharge: 0.05, ratePerKg: 53, handlingFee: 28 },
          { minWeight: 0.1, maxWeight: 0.24, ratePerKg: 53, handlingFee: 28 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 53, handlingFee: 28 },
          { minWeight: 0.5, maxWeight: 1, ratePerKg: 56, handlingFee: 30 },
          { minWeight: 1, maxWeight: 1.5, ratePerKg: 66, handlingFee: 30 },
          { minWeight: 1.5, maxWeight: 5, ratePerKg: 66, handlingFee: 30 },
        ],
      },
      {
        id: 'js_mx_gen', name: 'Mexico — General Cargo', code: 'MX0317-GEN',
        country: 'MX' as CountryCode, deliveryDays: { min: 8, max: 12 }, type: 'DDP',
        isActive: true, volumetricDivisor: 8000, maxWeight: 10, maxDimSum: 90,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 82, handlingFee: 20 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 84, handlingFee: 20 },
          { minWeight: 0.5, maxWeight: 1, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 1, maxWeight: 1.5, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 2, maxWeight: 2.5, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 2.5, maxWeight: 3, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 3, maxWeight: 5, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 5, maxWeight: 10, ratePerKg: 86, handlingFee: 22 },
        ],
      },
      {
        id: 'js_mx_dg', name: 'Mexico — Battery/DG', code: 'MX0317-DG',
        country: 'MX' as CountryCode, deliveryDays: { min: 8, max: 12 }, type: 'DDP-DG',
        isActive: true, volumetricDivisor: 8000, maxWeight: 10, maxDimSum: 90,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 87, handlingFee: 20 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 89, handlingFee: 20 },
          { minWeight: 0.5, maxWeight: 1, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 1, maxWeight: 1.5, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 2, maxWeight: 2.5, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 2.5, maxWeight: 3, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 3, maxWeight: 5, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 5, maxWeight: 10, ratePerKg: 91, handlingFee: 22 },
        ],
      },
    ],
  },
  js_express2: {
    id: 'js_express2',
    name: 'JS Express Old',
    effectiveDate: '2026-03-12',
    rating: 0,
    notes: '',
    isActive: true,
    createdAt: nowISO(),
    updatedAt: nowISO(),
    services: [
      {
        id: 'js2_au_z1_gen', name: 'AU Zone 1 — General Cargo', code: 'CAAU-GEN-Z1',
        country: 'AU' as CountryCode, zone: 'Zone 1', deliveryDays: { min: 8, max: 12 }, type: 'DDP',
        isActive: true, volumetricDivisor: 6000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 33, handlingFee: 20 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 33, handlingFee: 21 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 33, handlingFee: 21 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 33, handlingFee: 22 },
          { minWeight: 2, maxWeight: 5, ratePerKg: 33, handlingFee: 25 },
        ],
      },
      {
        id: 'js2_au_z2_gen', name: 'AU Zone 2 — General Cargo', code: 'CAAU-GEN-Z2',
        country: 'AU' as CountryCode, zone: 'Zone 2', deliveryDays: { min: 8, max: 12 }, type: 'DDP',
        isActive: true, volumetricDivisor: 6000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 33, handlingFee: 26 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 33, handlingFee: 26 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 33, handlingFee: 26 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 33, handlingFee: 28 },
          { minWeight: 2, maxWeight: 5, ratePerKg: 33, handlingFee: 38 },
        ],
      },
      {
        id: 'js2_au_z3_gen', name: 'AU Zone 3 — General Cargo', code: 'CAAU-GEN-Z3',
        country: 'AU' as CountryCode, zone: 'Zone 3', deliveryDays: { min: 8, max: 12 }, type: 'DDP',
        isActive: true, volumetricDivisor: 6000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 33, handlingFee: 47 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 33, handlingFee: 47 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 33, handlingFee: 66 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 33, handlingFee: 67 },
          { minWeight: 2, maxWeight: 5, ratePerKg: 33, handlingFee: 102.4 },
        ],
      },
      {
        id: 'js2_au_z1_dg', name: 'AU Zone 1 — Battery/DG', code: 'CAAU-DG-Z1',
        country: 'AU' as CountryCode, zone: 'Zone 1', deliveryDays: { min: 10, max: 15 }, type: 'DDP-DG',
        isActive: true, volumetricDivisor: 6000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 53, handlingFee: 20 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 53, handlingFee: 21 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 53, handlingFee: 21 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 53, handlingFee: 22 },
          { minWeight: 2, maxWeight: 4, ratePerKg: 53, handlingFee: 25 },
          { minWeight: 4, maxWeight: 5, ratePerKg: 53, handlingFee: 25 },
        ],
      },
      {
        id: 'js2_au_z2_dg', name: 'AU Zone 2 — Battery/DG', code: 'CAAU-DG-Z2',
        country: 'AU' as CountryCode, zone: 'Zone 2', deliveryDays: { min: 10, max: 15 }, type: 'DDP-DG',
        isActive: true, volumetricDivisor: 6000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 53, handlingFee: 26 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 53, handlingFee: 26 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 53, handlingFee: 26 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 53, handlingFee: 28 },
          { minWeight: 2, maxWeight: 4, ratePerKg: 53, handlingFee: 38 },
          { minWeight: 4, maxWeight: 5, ratePerKg: 53, handlingFee: 38 },
        ],
      },
      {
        id: 'js2_au_z3_dg', name: 'AU Zone 3 — Battery/DG', code: 'CAAU-DG-Z3',
        country: 'AU' as CountryCode, zone: 'Zone 3', deliveryDays: { min: 10, max: 15 }, type: 'DDP-DG',
        isActive: true, volumetricDivisor: 6000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 53, handlingFee: 47 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 53, handlingFee: 47 },
          { minWeight: 0.5, maxWeight: 1.5, ratePerKg: 53, handlingFee: 66 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 53, handlingFee: 67 },
          { minWeight: 2, maxWeight: 5, ratePerKg: 53, handlingFee: 102.4 },
        ],
      },
      {
        id: 'js2_ca_gen', name: 'Canada — General Cargo', code: 'CAAU-GEN-CA',
        country: 'CA' as CountryCode, deliveryDays: { min: 8, max: 12 }, type: 'DDP',
        isActive: true, volumetricDivisor: 6000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.1, minCharge: 0.05, ratePerKg: 48, handlingFee: 22 },
          { minWeight: 0.1, maxWeight: 0.24, ratePerKg: 48, handlingFee: 22 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 53, handlingFee: 22 },
          { minWeight: 0.5, maxWeight: 1, ratePerKg: 53, handlingFee: 25 },
          { minWeight: 1, maxWeight: 1.5, ratePerKg: 56, handlingFee: 25 },
          { minWeight: 1.5, maxWeight: 5, ratePerKg: 56, handlingFee: 25 },
        ],
      },
      {
        id: 'js2_ca_dg', name: 'Canada — Battery/DG', code: 'CAAU-DG-CA',
        country: 'CA' as CountryCode, deliveryDays: { min: 10, max: 15 }, type: 'DDP-DG',
        isActive: true, volumetricDivisor: 6000, maxWeight: 5, maxDimSum: 130,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.1, minCharge: 0.05, ratePerKg: 53, handlingFee: 28 },
          { minWeight: 0.1, maxWeight: 0.24, ratePerKg: 53, handlingFee: 28 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 53, handlingFee: 28 },
          { minWeight: 0.5, maxWeight: 1, ratePerKg: 56, handlingFee: 30 },
          { minWeight: 1, maxWeight: 1.5, ratePerKg: 66, handlingFee: 30 },
          { minWeight: 1.5, maxWeight: 5, ratePerKg: 66, handlingFee: 30 },
        ],
      },
      {
        id: 'js2_mx_gen', name: 'Mexico — General Cargo', code: 'MX0317-GEN',
        country: 'MX' as CountryCode, deliveryDays: { min: 8, max: 12 }, type: 'DDP',
        isActive: true, volumetricDivisor: 6000, maxWeight: 10, maxDimSum: 90,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 82, handlingFee: 20 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 84, handlingFee: 20 },
          { minWeight: 0.5, maxWeight: 1, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 1, maxWeight: 1.5, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 2, maxWeight: 2.5, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 2.5, maxWeight: 3, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 3, maxWeight: 5, ratePerKg: 86, handlingFee: 22 },
          { minWeight: 5, maxWeight: 10, ratePerKg: 86, handlingFee: 22 },
        ],
      },
      {
        id: 'js2_mx_dg', name: 'Mexico — Battery/DG', code: 'MX0317-DG',
        country: 'MX' as CountryCode, deliveryDays: { min: 8, max: 12 }, type: 'DDP-DG',
        isActive: true, volumetricDivisor: 6000, maxWeight: 10, maxDimSum: 90,
        maxDimensions: { l: 55, w: 40, h: 35 }, maxVolume: 0.077, oversizeSurcharge: 0,
        maxCompensation: { beforeTracking: 200, afterTracking: 200 },
        rates: [
          { minWeight: 0, maxWeight: 0.24, minCharge: 0.05, ratePerKg: 87, handlingFee: 20 },
          { minWeight: 0.24, maxWeight: 0.5, ratePerKg: 89, handlingFee: 20 },
          { minWeight: 0.5, maxWeight: 1, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 1, maxWeight: 1.5, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 1.5, maxWeight: 2, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 2, maxWeight: 2.5, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 2.5, maxWeight: 3, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 3, maxWeight: 5, ratePerKg: 91, handlingFee: 22 },
          { minWeight: 5, maxWeight: 10, ratePerKg: 91, handlingFee: 22 },
        ],
      },
    ],
  },
}
